---

- hosts: all
  become: true
  tasks:
    
    - name: install apache2 and php package for Debian
      apt:
        name: 
          - apache2
          - php
        state: latest
        update_cache: true
      when: ansible_distribution == "Debian"

    - name: install apache2 and php package for RedHat
      dnf:
        name: 
          - httpd
          - php
        state: latest
        update_cache: true
      when: ansible_distribution == "RedHat"

    - name: start httpd (RedHat)
      tags: apache,apache2, httpd
      service:
        name: httpd
        state: started
        enabled: true
      when: ansible_distribution == "RedHat"
   
    - name: change email address for admin in a conf file
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regex: '^ServerAdmin'
        line: ServerAdmin someone-new@nowhere.net
      when: ansible_distribution == "RedHat"
      register: httpd

    - name: restart httpd service
      service:
        name: httpd
        state: restarted
      when: httpd.changed 

    - name: copy default html site for apache site
      tags: apache,apache2,httpd
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

- hosts: workstation2
  become: true
  tasks:

    - name: install unzip 
      package:
        name: unzip

    - name: install terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.14.3/terraform_1.14.3_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root

